import { useEffect, useMemo, useState } from 'react';
import { api, CATEGORY_EMOJI, CATEGORY_LABEL, fmtShort, type Category, type Exercise, type GenSettings, type Proposal } from '../api';
import { navigate } from '../router';
import { categoryIds, useCategories } from '../categories';
import { CatChip, ErrorBox, Loading, useData, useToast } from '../ui';
import { HowTo } from './Player';
import { PlanForm, ProgramBody } from './Program';


/** "Prossimo programma": proposals generated by the AI (or the progression rules) to approve. */
export function NextProgramPage() {
  const toast = useToast();
  useCategories();
  const CATS: Category[] = categoryIds(true);
  const { data, error, reload } = useData(() => api.generator());
  const { data: exercises } = useData(() => api.exercises());
  const exMap = useMemo(() => new Map((exercises || []).map((e) => [e.id, e])), [exercises]);
  const [request, setRequest] = useState('');
  const [busy, setBusy] = useState(false);
  const [approving, setApproving] = useState<Proposal | null>(null);
  const [how, setHow] = useState<Exercise | null>(null);
  const [settings, setSettings] = useState<GenSettings | null>(null);
  const [showSettings, setShowSettings] = useState(false);

  useEffect(() => { if (data) setSettings(data.settings); }, [data]);

  if (error) return <ErrorBox error={error} retry={reload} />;
  if (!data || !settings) return <Loading />;

  const pending = data.proposals.filter((p) => p.status === 'pending');
  const history = data.proposals.filter((p) => p.status !== 'pending').slice(0, 6);

  const generate = async (engine: 'auto' | 'rules' = 'auto') => {
    setBusy(true);
    try {
      await api.propose({ request, engine });
      setRequest('');
      toast('Nuova proposta pronta ✨');
      reload();
    } catch (e) {
      toast((e as Error).message);
    } finally {
      setBusy(false);
    }
  };
  const reject = async (p: Proposal) => {
    await api.rejectProposal(p.id);
    reload();
  };
  const saveSettings = async () => {
    try {
      setSettings(await api.saveGenSettings(settings));
      toast('Preferenze salvate');
      setShowSettings(false);
    } catch (e) {
      toast((e as Error).message);
    }
  };
  const set = <K extends keyof GenSettings>(k: K, v: GenSettings[K]) => setSettings((s) => (s ? { ...s, [k]: v } : s));

  return (
    <div className="stack" style={{ gap: 20 }}>
      <div className="page-head">
        <div>
          <h1>Prossimo programma ✨</h1>
          <div className="sub">
            Quando un piano sta per finire, Moveo prepara il successivo in base a fatica, costanza e note.
            {data.ai ? ` Usa ${data.model}; se non risponde, le regole di progressione.` : ' Chiave AI non configurata: usa le regole di progressione.'}
          </div>
        </div>
        <button className="btn ghost" onClick={() => setShowSettings((v) => !v)}>⚙️ Preferenze</button>
      </div>

      {showSettings && (
        <section className="card stack">
          <h2>Preferenze del generatore</h2>
          <label className="field">I tuoi obiettivi
            <textarea className="input" style={{ minHeight: 80, fontFamily: 'inherit' }} value={settings.goals} onChange={(e) => set('goals', e.target.value)} />
          </label>
          <div className="grid-3">
            <label className="field">Sessioni a settimana (max)<input className="input" type="number" min={1} max={6} value={settings.sessionsPerWeek} onChange={(e) => set('sessionsPerWeek', Number(e.target.value))} /></label>
            <label className="field">Minuti per sessione (max)<input className="input" type="number" min={10} max={90} value={settings.maxMinutes} onChange={(e) => set('maxMinutes', Number(e.target.value))} /></label>
            <label className="switch" style={{ alignSelf: 'end', minHeight: 42 }}><input type="checkbox" checked={settings.auto} onChange={(e) => set('auto', e.target.checked)} /> Proponi in automatico a fine piano</label>
          </div>
          <div className="field">Discipline preferite
            <div className="row">
              {CATS.map((c) => (
                <button key={c} type="button" className={`chip ${settings.categories.includes(c) ? 'on' : ''}`}
                  onClick={() => set('categories', settings.categories.includes(c) ? settings.categories.filter((x) => x !== c) : [...settings.categories, c])}>
                  {CATEGORY_EMOJI[c]} {CATEGORY_LABEL[c]}
                </button>
              ))}
            </div>
          </div>
          <div className="row"><button className="btn primary" onClick={saveSettings}>Salva</button></div>
        </section>
      )}

      <section className="card stack">
        <h2>Chiedi un nuovo programma</h2>
        <textarea className="input" style={{ minHeight: 70, fontFamily: 'inherit' }} value={request} onChange={(e) => setRequest(e.target.value)}
          placeholder="Facoltativo. Es. «4 settimane di surf con più remata», «solo 20 minuti, ho poco tempo», «la spalla destra mi dà fastidio»" />
        <div className="row">
          <button className="btn primary" onClick={() => generate('auto')} disabled={busy}>{busy ? 'Sto preparando la proposta…' : '✨ Genera proposta'}</button>
          <button className="btn ghost sm" onClick={() => generate('rules')} disabled={busy}>Solo regole di progressione</button>
        </div>
        {busy && <div className="faint small">Con l'AI può servire fino a un minuto: la proposta viene anche verificata (volumi, durata, scarico).</div>}
        {data.nearEnd.length > 0 && <div className="faint small">Piani quasi conclusi: {data.nearEnd.map((n) => `${n.programId} (${n.done}/${n.total})`).join(', ')}</div>}
      </section>

      {pending.length === 0 && <div className="empty">Nessuna proposta in attesa. Ne arriverà una quando il piano attuale sarà quasi finito, oppure chiedila qui sopra.</div>}

      {pending.map((p) => (
        <div key={p.id} className="stack" style={{ gap: 16 }}>
          <section className={`card hero stack cat-${p.program.category}`}>
            <div className="row">
              <span className="chip">{p.engine === 'ai' ? `✨ AI · ${p.model}` : '📐 Regole di progressione'}</span>
              <CatChip category={p.program.category} />
              <span className="chip">{p.program.schedule?.length} settimane</span>
              <span className="faint small">{fmtShort(p.createdAt)}</span>
            </div>
            <h1>{p.program.title}</h1>
            {p.program.summary && <p className="muted" style={{ fontSize: '1.05rem' }}>{p.program.summary}</p>}
            {p.rationale && <div className="alert info">💡 {p.rationale}</div>}
            {p.request && <div className="faint small">Richiesta: “{p.request}”</div>}
            {p.warnings.map((w) => <div key={w} className="alert small">⚠️ {w}</div>)}
            <div className="row">
              <button className="btn primary lg" onClick={() => setApproving(p)}>✓ Approva e pianifica</button>
              <button className="btn" onClick={async () => { await api.approveProposal(p.id, null); toast('Aggiunto ai programmi'); navigate(`/programmi/${p.program.id}`); }}>Salva senza pianificare</button>
              <button className="btn danger" onClick={() => reject(p)}>Scarta</button>
            </div>
          </section>
          <ProgramBody p={p.program} exMap={exMap} onHow={setHow} tryable={false} />
        </div>
      ))}

      {history.length > 0 && (
        <section className="card stack">
          <h2>Proposte precedenti</h2>
          {history.map((p) => (
            <div key={p.id} className="row between small">
              <span>{p.program.title} <span className="faint">· {p.engine === 'ai' ? 'AI' : 'regole'} · {fmtShort(p.createdAt)}</span></span>
              {p.status === 'approved'
                ? <button className="btn sm ghost" onClick={() => navigate(`/programmi/${p.program.id}`)}>approvata · apri →</button>
                : <span className="faint">scartata</span>}
            </div>
          ))}
        </section>
      )}

      {approving && (
        <PlanForm program={approving.program} heading={`Approva: ${approving.program.title}`} submitLabel="Approva e crea piano"
          onSubmit={async (input) => { await api.approveProposal(approving.id, input); }}
          onClose={() => setApproving(null)}
          onDone={() => { setApproving(null); toast('Programma approvato e messo in Calendary 🗓️'); navigate('/piano'); }} />
      )}
      {how && <HowTo ex={how} onClose={() => setHow(null)} />}
    </div>
  );
}
